### PR TITLE
Sensor data classes

### PR DESCRIPTION
**Pull request by usephysics**
Create sensor data classes in sensors.py and their unit tests, which now handle update functionality for sensor data generation.

See [this basecamp task](https://3.basecamp.com/4075148/buckets/9442051/todos/3103132779) for more info.

Each class has an update() function and a calibration parameter. All calibration parameters are currently set at 1.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12)

### CODE REVIEW

**Review by dwkletke — CHANGES_REQUESTED** [review]
Overall, this is great work! I think we could add constants for calibration values for the sensors into `data_generator.py` and remove the need for default values in the `Sensors` class. However that could be done later when we actual have calibration values to set.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-:-MTa2YiVEHxvx6-zRJdX:b-1gbf59)* status: all files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @usephysics)

___
*[generated_files/ground_truth.txt, line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-MTa-cyh0M05wWLEnJ8-:-MTa-cyi3KBXGLZxMAyJ:b-dekzun) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/2fb5abde969fa799b083c17c9079dae6aee48aac/generated_files/ground_truth.txt#L0)):*
I don't think ground_truth.txt and sensor_data.txt should be tracked on git yet. We need to devise a better plan for how we want to keep the generated files in case we need to keep multiple sets.
___
*[generated_files/sensor_data.txt, line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-MTa2P0xAslDYrP1Jtvr:-MTa2P0xAslDYrP1Jtvs:b2nreh6) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/2fb5abde969fa799b083c17c9079dae6aee48aac/generated_files/sensor_data.txt#L0)):*
Same as above.

**Comment by usephysics** [comment]
> Overall, this is great work! I think we could add constants for calibration values for the sensors into `data_generator.py` and remove the need for default values in the `Sensors` class. However that could be done later when we actual have calibration values to set.

I just have the default value right now since we don't have any calibration values at the moment. I don't think it hurts at all to have it there, even after we set values in data_generator.py

> _[generated_files/ground_truth.txt, line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-MTa-cyh0M05wWLEnJ8-:-MTa-cyi3KBXGLZxMAyJ:b-dekzun) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/2fb5abde969fa799b083c17c9079dae6aee48aac/generated_files/ground_truth.txt#L0)):_
> I don't think ground_truth.txt and sensor_data.txt should be tracked on git yet. We need to devise a better plan for how we want to keep the generated files in case we need to keep multiple sets.
> 
> _[generated_files/sensor_data.txt, line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-MTa2P0xAslDYrP1Jtvr:-MTa2P0xAslDYrP1Jtvs:b2nreh6) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/2fb5abde969fa799b083c17c9079dae6aee48aac/generated_files/sensor_data.txt#L0)):_
> Same as above.

I mentioned this [earlier](https://github.com/waterloo-rocketry/state_estimation/pull/11#pullrequestreview-558844721), I think they should be added to .gitignore.

**Review by dwkletke — CHANGES_REQUESTED** [review]
Yeah I agree. I meant to amend my statement to say that the default value should remain even after we set the constants.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-:-MTcE6L49dybPdKmsGCn:b52f3kd)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @usephysics)

___
*[sensors.py, line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-MTep79jDg9EaChImZIo:-MTep79kDMiX0HsfgtyB:b-394tqb) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/2fb5abde969fa799b083c17c9079dae6aee48aac/sensors.py#L15)):*
> ```
> def update(self, rocket):
> ```
I also just noticed that the rocket parameter for each sensor needs to be added to the docstrings!
___
*[generated_files/sensor_data.txt, line  at r1](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-MTa2P0xAslDYrP1Jtvr:-MTcLKJR6Lubw-N2DBSX:b-jn2ms6) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/2fb5abde969fa799b083c17c9079dae6aee48aac/generated_files/sensor_data.txt#L)):*
<details><summary><i>Previously, usephysics (Ryan Tan) wrote…</i></summary><blockquote>

I mentioned this [earlier](https://github.com/waterloo-rocketry/state_estimation/pull/11#pullrequestreview-558844721), I think they should be added to .gitignore. 
</blockquote></details>

I think for now that is fine. However the generated files could still be unstaged when committing without being in the .gitignore.

In the future we will want a structure for keeping the generated files but that is not required right now.

**Review by dwkletke — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/12#-:-MU4n1-qAg-v72_XVHRG:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @usephysics)

**Pull request merged**
